import Image from 'next/image';
import Link from 'next/link';
import { ActionLink, Arrow } from '../components/ui';

export default function HomePage() {
  return <main id="main-content">
    <section className="hero container">
      <div className="hero-copy"><p className="eyebrow"><span />MAXBET WHOLESALE PHARMACY</p><h1>Wholesale pharmacy<br /><em>for your business.</em></h1><p className="hero-description">A dedicated space for your pharmacy to explore our catalogue and access Maxbet wholesale services.</p><div className="actions"><ActionLink href="/products">Explore the catalogue</ActionLink><Link className="text-link" href="/register">About account access <Arrow diagonal /></Link></div><div className="hero-note"><span className="small-cross" aria-hidden="true">+</span><p>For pharmacy businesses in Ghana.<br /><strong>Prices and purchasing are reserved for approved accounts.</strong></p></div></div>
      <div className="hero-visual" aria-label="Maxbet Pharmacy Ltd brand presentation"><div className="visual-grid" /><span className="visual-label">MAXBET / GHANA</span><div className="brand-orbit orbit-one" /><div className="brand-orbit orbit-two" /><div className="logo-plaque"><Image src="/brand/maxbet-logo.png" alt="Maxbet Pharmacy Ltd logo: green mortar and pestle with blue and red lettering" width={116} height={116} unoptimized /><span className="plaque-line" /><p>MAXBET<br /><strong>PHARMACY LTD</strong></p><span className="plaque-caption">WHOLESALE PHARMACY</span></div><div className="visual-bottom"><span>For pharmacy businesses.<br />Wholesale account access.</span><span className="round-arrow"><Arrow diagonal /></span></div></div>
    </section>
    <section className="access-strip"><div className="container access-strip-inner"><span className="section-index">01 / ACCESS</span><p>Start with the catalogue.<br /><strong>Continue with an approved account.</strong></p><Link href="/register" className="text-link">Understand account access <Arrow /></Link></div></section>
    <section className="container section" id="how-it-works"><div className="section-heading"><div><p className="eyebrow">A CLEAR PATH TO GETTING STARTED</p><h2>From browsing<br />to business access.</h2></div><p>The platform is taking shape. Here is how the customer experience will work when services open.</p></div><div className="steps-grid">{[{n:'01',title:'Explore the catalogue',text:'Discover the products Maxbet offers through a public catalogue.',href:'/products',label:'Catalogue preview'},{n:'02',title:'Request an account',text:'Submit your business details when account registration opens.',href:'/register',label:'Account information'},{n:'03',title:'Access wholesale services',text:'Once approved, sign in to view wholesale prices, availability and purchasing.',href:'/login',label:'Sign-in information'}].map(step=><article className="step-card" key={step.n}><span className="step-number">{step.n}</span><h3>{step.title}</h3><p>{step.text}</p><Link href={step.href}>{step.label}<Arrow diagonal /></Link></article>)}</div></section>
    <section className="container bottom-callout"><div><p className="eyebrow">BUSINESS ACCOUNT ACCESS</p><h2>Your next step with Maxbet.</h2><p>Learn what an approved account will give your pharmacy access to.</p></div><ActionLink href="/register">View account information</ActionLink></section>
  </main>;
}

