import type { Metadata } from 'next';
import { ActionLink, Badge, Field, Notice } from '../../components/ui';
export const metadata: Metadata = { title: 'Visual system', robots: { index: false, follow: false } };
const swatches = [{name:'Primary green',hex:'#007D42'},{name:'Brand blue',hex:'#282D83'},{name:'Red accent',hex:'#BB302D'},{name:'Text',hex:'#192D27'},{name:'Soft surface',hex:'#EDF7F0'}];
export default function BrandPage() {
  return <main id="main-content" className="container"><div className="page-intro"><p className="eyebrow">PHASE 2 / DESIGN REFERENCE</p><h1>The Maxbet visual system.</h1><p>A shared foundation for clear, consistent customer and staff experiences. These are component examples, not live account information.</p></div><div className="page-body">
    <section className="showcase-section"><h2>01 / Colour</h2><p>Green leads actions. Blue carries the business identity and keyboard focus. The red accent complements the supplied logo; status colours always appear with a text label.</p><div className="swatches">{swatches.map(s=><div className="swatch" key={s.name}><div className="swatch-color" style={{background:s.hex}} /><p>{s.name}<br /><code>{s.hex}</code></p></div>)}</div></section>
    <section className="showcase-section"><h2>02 / Typography</h2><p>System sans-serif typography keeps the experience fast and readable. The original logo lettering remains intact.</p><div className="type-samples"><p className="eyebrow">SECTION LABEL</p><h3>Clear information. Comfortable reading.</h3><p>Use plain language, short labels and enough space to scan information.</p></div></section>
    <section className="showcase-section"><h2>03 / Actions</h2><p>One clear primary action, a quieter secondary action, and a visibly unavailable state.</p><div className="component-row"><ActionLink href="/products">Explore catalogue</ActionLink><ActionLink href="/register" secondary>Account information</ActionLink><button className="button" disabled>Unavailable example</button></div></section>
    <section className="showcase-section"><h2>04 / Form fields</h2><p>Illustrative, read-only fields. No details are collected or submitted.</p><div className="field-grid"><Field id="example-business" label="Business name" value="Example Pharmacy" readOnly hint="Example only — this is not an application." /><Field id="example-email" label="Email address" value="" placeholder="name@example.com" readOnly error="Example error: enter a valid email address." /><Field id="example-disabled" label="Account reference" value="Not available" disabled /></div></section>
    <section className="showcase-section"><h2>05 / Status and guidance</h2><p>Example states are communicated with words as well as colour.</p><div className="component-row"><Badge>Draft example</Badge><Badge tone="success">Approved example</Badge><Badge tone="warning">Pending example</Badge><Badge tone="error">Needs attention example</Badge></div><div style={{marginTop:24}}><Notice title="Keep the next step clear">Explain what happened and what the customer can do next, using concise, direct language.</Notice></div></section>
    <section className="showcase-section"><h2>06 / Expandable guidance</h2><p>Keyboard-accessible disclosure for supporting information.</p><details className="reference-details"><summary>How will prices appear?</summary><p>Wholesale prices will be available only after an approved customer signs in. Public pages will focus on product information.</p></details></section>
  </div></main>;
}
